name: Deploy to the Server

on:
  push:
    branches:
      - master  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # - name: Install sshpass
    #   run: sudo apt-get install -y sshpass

    - name: Pull latest changes from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@66.29.130.146 << 'EOF'
        cd /home/adbond/web/api.adbondharvestandhomes.com/public_html
        git pull https://${{ secrets.GH_ACCESS_TOKEN }}@https://github.com/Adbond-Harvest-and-Homes/Adbond-2.0-Project-Backend.git master
        EOF

    - name: Run post-deployment scripts
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@66.29.130.146 << 'EOF'
        cd /home/adbond/web/api.adbondharvestandhomes.com/public_html

        # Run migrations for the main database
        php artisan migrate --force

        # Seed The data
        php artisan db:seed --class=DatabaseSeeder

        # Install Composer dependencies
        composer install --no-dev --optimize-autoloader

        # Clear various caches
        php artisan route:clear
        php artisan config:clear
        php artisan cache:clear
        php artisan view:clear

        # Create Request Docs
        php artisan laravel-request-docs:export

        EOF
